export default {
    AGENT_CREATE_REQUEST: "AGENT_CREATE_REQUEST",
    AGENT_CREATE_SUCCESS: "AGENT_CREATE_SUCCESS",
    AGENT_CREATE_FAILURE: "AGENT_CREATE_FAILURE",

    AGENT_GET_REQUEST: "AGENT_GET_REQUEST",
    AGENT_GET_SUCCESS: "AGENT_GET_SUCCESS",
    AGENT_GET_FAILURE: "AGENT_GET_FAILURE",

    AGENT_FETCH_REQUEST: "AGENT_FETCH_REQUEST",
    AGENT_FETCH_SUCCESS: "AGENT_FETCH_SUCCESS",
    AGENT_FETCH_FAILURE: "AGENT_FETCH_FAILURE",

    CLEAR_AGENT_STATE: "CLEAR_AGENT_STATE"
}