export default {
    CHECK_AUTH_REQUEST: "CHECK_AUTH_REQUEST",
    CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS",
    CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE"
}